#! /usr/bin/env python3
print(" ___    ____     __     __  ____   ___   ____   ____     ___   ____  _         ")
print("|   \  l    j   /  ]   /  ]l    j /   \ |    \ |    \   /  _] /    T| T        ")
print("|    \  |  T   /  /   /  /  |  T Y     Y|  D  )|  D  ) /  [_ Y  o  || |        ")
print("|  D  Y |  |  /  /   /  /   |  | |  O  ||    / |    / Y    _]|     || l___     ")
print("|     | |  | /   \_ /   \_  |  | |     ||    \ |    \ |   [_ |  _  ||     T    ")
print("|     | j  l \     |\     | j  l l     !|  .  Y|  .  Y|     T|  |  ||     |    ")
print("l_____j|____j \____j \____j|____j \___/ l__j\_jl__j\_jl_____jl__j__jl_____j    ")
print("          Elaborada por un villano                  Creado x : TroyanInfec ")
print("")
print("                   *Para pruebas de seguridad en facebook*")
print("")
print("")
#Entrada de datos
a=input("Ingrese el nombre:")
b=input(f"Ingrese el apellido paterno de {a}:")
c=input(f"Ingrese el apellido materno de {a} {b}:")
d=input(f"Ingrese día de cumpleaños de {a} {b} {c}:")
f=input(f"Ingrese mes de cumpleaños de {a} {b} {c}:")
g=input(f"Ingrese el año de cumpleaños de {a} {b} {c}:")
import os
os.system('clear')

print(" ___    ____     __     __  ____   ___   ____   ____     ___   ____  _         ")
print("|   \  l    j   /  ]   /  ]l    j /   \ |    \ |    \   /  _] /    T| T        ")
print("|    \  |  T   /  /   /  /  |  T Y     Y|  D  )|  D  ) /  [_ Y  o  || |        ")
print("|  D  Y |  |  /  /   /  /   |  | |  O  ||    / |    / Y    _]|     || l___     ")
print("|     | |  | /   \_ /   \_  |  | |     ||    \ |    \ |   [_ |  _  ||     T    ")
print("|     | j  l \     |\     | j  l l     !|  .  Y|  .  Y|     T|  |  ||     |    ")
print("l_____j|____j \____j \____j|____j \___/ l__j\_jl__j\_jl_____jl__j__jl_____j    ")
print("          Elaborada por un villano                  Creado x : TroyanInfec ")
print("")
print("")
print("Diccionario generado :")
print("")
#Las posibles contraseñas , en facebook solo se puede hacer 20 intentos
print(f"{a.capitalize()}_{d}")
print(f"{a.capitalize()}.{d}")
print(f"{a.capitalize()}{d}")
print(f"{a.capitalize()}{d}{f}")
print(f"{a.capitalize()}{d}{f}{g}")
print(f"{a.lower()}_{d}")
print(f"{a.lower()}.{d}")
print(f"{a.lower()}{d}")
print(f"{a.lower()}{d}{f}")
print(f"{a.lower()}{d}{f}{g}")
print(f"{b.capitalize()}_{d}")
print(f"{b.capitalize()}.{d}")
print(f"{b.capitalize()}{d}")
print(f"{b.capitalize()}{d}{f}")
print(f"{b.capitalize()}{d}{f}{g}")
print(f"{b.lower()}_{d}")
print(f"{b.lower()}.{d}")
print(f"{b.lower()}{d}")
print(f"{b.lower()}{d}{f}")
print(f"{b.lower()}{d}{f}{g}")
print(f"{c.capitalize()}_{d}")
print(f"{c.capitalize()}.{d}")
print(f"{c.capitalize()}{d}")
print(f"{c.capitalize()}{d}{f}")
print(f"{c.capitalize()}{d}{f}{g}")
print(f"{c.lower()}_{d}")
print(f"{c.lower()}.{d}")
print(f"{c.lower()}{d}")
print(f"{c.lower()}{d}{f}")
print(f"{c.lower()}{d}{f}{g}")
